### ISSUE TITLE
add to f-droid

### ISSUE THREAD

**Issue by OmlineEditor** [kittoku/Open-SSTP-Client#119]
Please add your program to the catalog https://f-droid.org/

here is an approximate description of how to add:
https://f-droid.org/en/docs/Inclusion_How-To/

**Comment by kittoku** [comment]
Sorry, but I don't intend to add a way to release besides Google Play and apk.

FYI, there is someone who run [a F-froif repository of this app](https://apt.izzysoft.de/fdroid/index/apk/kittoku.osc).

**Comment by OmlineEditor** [comment]
will you allow me to add the program to the f-droid website if someone else does it?

**Comment by kittoku** [comment]
This is an OSS app!

If you are following [the licence](https://github.com/kittoku/Open-SSTP-Client/blob/main/LICENSE), I am not in a position to allow or disallow (^_^).

**Comment by licaon-kter** [comment]
A Fastlane folder structure would be nice, ref: https://gitlab.com/-/snippets/1895688

**Comment by licaon-kter** [comment]
This draft recipe builds fine **metadata/kittoku.osc.yml** and reproducible :tada: 
```
License: Unknown
SourceCode: https://github.com/kittoku/Open-SSTP-Client
IssueTracker: https://github.com/kittoku/Open-SSTP-Client/issues

RepoType: git
Repo: https://github.com/kittoku/Open-SSTP-Client
Binaries: https://github.com/kittoku/Open-SSTP-Client/releases/download/v%v/osc-%v.apk

Builds:
  - versionName: 1.9.1
    versionCode: 42
    commit: 4f1994fda0efba784c7880c79c6165de973eff5c
    subdir: app
    gradle:
      - yes

AllowedAPKSigningKeys: 35a0107f1c39134a4ee7c03272fdccb80aac4b864583d063fef63758277de3d5

AutoUpdateMode: None
UpdateCheckMode: Tags
```

up next, looking at your APK in https://github.com/kittoku/Open-SSTP-Client/releases/tag/v1.9.1

```
$ apksigtool parse --json osc-1.9.1.ap| jq -r '.pairs[].value._type'
APKSignatureSchemeBlock
DependencyInfoBlock
VerityPaddingBlock
```
hmm looks like you have the `DependencyInfoBlock` thing :disappointed: 

Can you add this fix: https://gitlab.com/fdroid/fdroidserver/-/issues/1056#note_1218193185 ? @kittoku 
```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

we'll need a new version, tag, release
